/*
 * Copyright (c) 2020 optile GmbH
 * https://www.optile.net
 *
 * This file is open source and available under the MIT license.
 * See the LICENSE file for more information.
 */

package net.optile.payment.model;

import java.math.BigDecimal;
import java.net.URL;
import java.util.List;

/**
 * Payment plan to pay by schedule.
 */
public class InstallmentsPlan {
    /** unique plan id. */
    private String id;
    /** Collection of installment's info (mandatory) */
    private List<InstallmentItem> schedule;
    /** An array of possible payment days (optional) */
    private List<Integer> dueDays;

    /** Currency value (mandatory) */
    private String currency;

    /** The interest amount. */
    private BigDecimal interestAmount;
    /** Fee for opening up an installment plan (optional) */
    private BigDecimal installmentSetupFee;
    /** Constant periodic fee for each installment item  (optional) */
    private BigDecimal installmentPeriodicFee;
    /**
     * The total fee for the installment payment (or serviceChargeAmount) (mandatory).
     * Includes all periodic fees and the installment set-up fee.
     */
    private BigDecimal installmentFee;
    /** The total transaction amount after calculation including all fees and interest (mandatory) */
    private BigDecimal totalAmount;

    /** The interest rate per year in percentages (Nominalzins or Sollzins) (mandatory) */
    private BigDecimal nominalInterestRate;
    /** The effective interest rate per year in percentages (Effektivzins) (mandatory) */
    private BigDecimal effectiveInterestRate;

    /** An URL to the Credit Information document (optional) */
    private URL creditInformationUrl;
    /** An URL to terms and conditions information document (optional) */
    private URL termsAndConditionsUrl;
    /** An URL to the data privacy consent document (optional) */
    private URL dataPrivacyConsentUrl;
    /** An URL to the installment plan logo (optional) */
    private URL logoUrl;
    /** Description of the installments plan (optional) */
    private String description;
    /** Number of installments in the installments plan (optional) */
    private Integer numberOfInstallments;

    /**
     * Gets plan id.
     *
     * @return Plan id.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets plan id.
     *
     * @param id Plan id.
     */
    public void setId(final String id) {
        this.id = id;
    }

    /**
     * Gets collection of particular schedule.
     *
     * @return Installments information.
     */
    public List<InstallmentItem> getSchedule() {
        return schedule;
    }

    /**
     * Sets schedule information.<br>
     * This information should be generated by adapter if it is not provided by PSP: use schedule count and due amount to do this.
     *
     * @param schedule Collection of schedule information.
     */
    public void setSchedule(final List<InstallmentItem> schedule) {
        this.schedule = schedule;
    }

    /**
     * Gets currency.
     *
     * @return Currency value.
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets currency.
     *
     * @param currency Currency value.
     */
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    /**
     * Gets total amount what customer should pay.
     *
     * @return Amount value in major units.
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets total amount what customer should pay by this plan.
     *
     * @param totalAmount Amount value in major units.
     */
    public void setTotalAmount(final BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Gets a set-up fee of the installments plan.
     *
     * @return installments setup fee
     */
    public BigDecimal getInstallmentSetupFee() {
        return installmentSetupFee;
    }

    /**
     * Sets a set-up fee of the installments plan.
     *
     * @param installmentSetupFee startup fee of the installments plan
     */
    public void setInstallmentSetupFee(final BigDecimal installmentSetupFee) {
        this.installmentSetupFee = installmentSetupFee;
    }

    /**
     * Gets a constant periodic fee for each installment item
     *
     * @return installment periodic fee
     */
    public BigDecimal getInstallmentPeriodicFee() {
        return installmentPeriodicFee;
    }

    /**
     * Sets a constant periodic fee for each installment item.
     *
     * @param installmentPeriodicFee installment periodic fee
     */
    public void setInstallmentPeriodicFee(final BigDecimal installmentPeriodicFee) {
        this.installmentPeriodicFee = installmentPeriodicFee;
    }

    /**
     * Gets service fee for this schedule plan.
     *
     * @return Amount value in major units.
     */
    public BigDecimal getInstallmentFee() {
        return installmentFee;
    }

    /**
     * Sets service fee for this schedule plan.
     *
     * @param installmentFee Amount value in major units.
     */
    public void setInstallmentFee(final BigDecimal installmentFee) {
        this.installmentFee = installmentFee;
    }

    /**
     * Gets interest rate per year in percentages (Nominalzins or Sollzins).
     *
     * @return Rate in percentages.
     */
    public BigDecimal getNominalInterestRate() {
        return nominalInterestRate;
    }

    /**
     * Sets interest rate per year in percentages.
     *
     * @param nominalInterestRate Rate in percentages.
     */
    public void setNominalInterestRate(final BigDecimal nominalInterestRate) {
        this.nominalInterestRate = nominalInterestRate;
    }

    /**
     * Gets the effective interest rate per year in percentages (Effektivzins).
     *
     * @return Rate in percentages.
     */
    public BigDecimal getEffectiveInterestRate() {
        return effectiveInterestRate;
    }

    /**
     * Sets the effective interest rate per year in percentages.
     *
     * @param effectiveInterestRate Rate in percentages.
     */
    public void setEffectiveInterestRate(final BigDecimal effectiveInterestRate) {
        this.effectiveInterestRate = effectiveInterestRate;
    }

    /**
     * Gets an URL to the Credit Information document.
     *
     * @return URL object.
     */
    public URL getCreditInformationUrl() {
        return creditInformationUrl;
    }

    /**
     * Sets an URL to the Credit Information document.
     *
     * @param creditInformationUrl URL object.
     */
    public void setCreditInformationUrl(final URL creditInformationUrl) {
        this.creditInformationUrl = creditInformationUrl;
    }

    /**
     * Gets an URL to terms and conditions information document.
     *
     * @return URL object.
     */
    public URL getTermsAndConditionsUrl() {
        return termsAndConditionsUrl;
    }

    /**
     * Sets an URL to terms and conditions information document.
     *
     * @param termsAndConditionsUrl URL object.
     */
    public void setTermsAndConditionsUrl(final URL termsAndConditionsUrl) {
        this.termsAndConditionsUrl = termsAndConditionsUrl;
    }

    /**
     * Gets an URL to the data privacy consent document.
     *
     * @return URL object.
     */
    public URL getDataPrivacyConsentUrl() {
        return dataPrivacyConsentUrl;
    }

    /**
     * Sets an URL to the data privacy consent document.
     *
     * @param dataPrivacyConsentUrl URL object.
     */
    public void setDataPrivacyConsentUrl(final URL dataPrivacyConsentUrl) {
        this.dataPrivacyConsentUrl = dataPrivacyConsentUrl;
    }

    /**
     * Gets interest amount.
     *
     * @return Amount value in major units.
     */
    public BigDecimal getInterestAmount() {
        return interestAmount;
    }

    /**
     * Sets interest amount.
     *
     * @param interestAmount Amount value in major units.
     */
    public void setInterestAmount(final BigDecimal interestAmount) {
        this.interestAmount = interestAmount;
    }

    /**
     * Gets a collection of possible payment days provided by provider.
     *
     * @return A collection object with calendar days.
     */
    public List<Integer> getDueDays() {
        return dueDays;
    }

    /**
     * Sets a collection of possible payment days provided by provider.
     *
     * @param dueDays A collection with calendar days.
     */
    public void setDueDays(final List<Integer> dueDays) {
        this.dueDays = dueDays;
    }

    /**
     * Gets an URL to logo of the installments plan.
     *
     * @return URL object.
     */
    public URL getLogoUrl() {
        return logoUrl;
    }

    /**
     * Sets an URL to a logo of the installments plan. (Optional)
     *
     * @param logoUrl URL object.
     */
    public void setLogoUrl(final URL logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * Gets a description of the installments plan.
     *
     * @return description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets a description of the installments plan. (Optional)
     *
     * @param description description
     */
    public void setDescription(final String description) {
        this.description = description;
    }

    /**
     * Gets a number of installments in the installment plan.
     *
     * @return number of installments
     */
    public Integer getNumberOfInstallments() {
        return numberOfInstallments;
    }

    /**
     * Sets a number of installments in the installment plan. (Optional)
     *
     * @param numberOfInstallments number of installments
     */
    public void setNumberOfInstallments(final Integer numberOfInstallments) {
        this.numberOfInstallments = numberOfInstallments;
    }
}
