# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.176.0"

default_platform :android

platform :android do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Example SDK - Deploy internal version to PlayStore"
  lane :uploadExampleSDK do
    gradle(task: "clean")
    gradle(task: ":example-sdk:assembleRelease")
    supply(
        track: 'internal',
	package_name: 'com.payoneer.mrs.examplesdk'
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Example Shop - Deploy internal version to PlayStore"
  lane :uploadExampleShop do
    gradle(task: "clean")
    gradle(task: ":example-shop:assembleRelease")
    supply(
        track: 'internal',
	package_name: 'com.payoneer.mrs.exampleshop'
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
