
name: Pull Request
on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  build:

    runs-on: jdk8

    steps:
      - uses: actions/checkout@v2

      - name: Run Test Script
        env:
          CI: true
          BRANCH_STRATEGY: release
        run: |
          env
          .ci/test.sh

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_FOOTER: "Payoneer's Github Actions"
        if: failure()
